pipeline:
  name: iac-gcp-VM
  identifier: iacgcpVM
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Githubconnector
        repoName: harness-IAC-practice
        build: <+input>
  stages:
    - stage:
        name: terraform init
        identifier: terraform_init
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: init
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      cat <<EOF > /tmp/gcp-key.json
                      <+secrets.getValue("gcp_service_key")>
                      EOF

                      export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json

                      echo "Initializing for project: $project_id"
                      terraform init -backend-config="bucket=$state_file_bucket"
                    envVariables:
                      state_file_bucket: <+stage.variables.state_file_bucket>
                      project_id: <+stage.variables.project_id>
              - step:
                  type: Run
                  name: plan
                  identifier: plan
                  spec:
                    shell: Sh
                    command: |-
                      cat <<EOF > /tmp/gcp-key.json
                      <+secrets.getValue("gcp_service_key")>
                      EOF

                      export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json
                      terraform plan
                    envVariables:
                      TF_VAR_state_file_bucket: <+stage.variables.state_file_bucket>
                      TF_VAR_project_id: <+stage.variables.project_id>
        variables:
          - name: state_file_bucket
            type: String
            description: ""
            required: true
            value: prashant-8874
          - name: project_id
            type: String
            description: ""
            required: true
            value: elite-totality-418717
  delegateSelectors:
    - docker-delegate
